writingImplements:
    - feather
    - stick
    - blaze_rod
    - arrow
writingSurfaces:
    - bedrock
    - clay
    - cobblestone
    - mossy_cobblestone
    - ice
    - sandstone
    - obsidian
    - stone
    - bookshelf
    - brick
    - glass
    - step
    - glowstone
    - nether_brick
    - log
    - wood
    - wood_stairs
    - cobblestone_stairs
    - brick_stairs
    - smooth_stairs
    - nether_brick_stairs
    #- craftingtable
    #- chest
    #- door
    - sign
    - thin_glass
    - wood_plate
    - stone_plate
    - coal_ore
    - gold_ore
    - lapis_ore
    - redstone_ore
    - iron_ore
    - gold_block
    - lapis_block
    - iron_block
    - water_lily
inks:
    rose_red: dark_red
    dandelion_yellow: yellow
    lapis_lazuli: blue
    cactus_green: dark_green
    ink_sac: black
    bone_meal: white
    glowstone_dust: gold
    cyan_dye: blue
    purple_dye: light_purple
    gray_dye: dark_gray
    light_blue_dye: aqua
    coal: dark_gray
    pink_dye: red
    lime_dye: green
    magenta_dye: dark_purple
    light_gray_dye: gray
    redstone: magic
    #cocoa_beans: # no brown
    #orange_dye: # no orange


