nextPaperID: -1
paperLengthLineCap: 17
consumeInk: false
autoRead: true
magicInkDecoder: dragon_egg
writingImplements:
    - feather
    - stick
    - blaze_rod
    - arrow
writingSurfaces:
    #- bed_block
    - bedrock
    - bookshelf
    #- brewing_stand
    - brick
    - brick_stairs
    - burning_furnace   
    #- chest
    - clay
    - cobblestone
    - cobblestone_stairs
    #- dispenser
    - double_step
    #- dragon_egg
    #- enchantment_table
    #- furnace
    - mossy_cobblestone
    - ice
    - sandstone
    - sign
    - sign_post
    - wall_sign
    - obsidian
    - stone
    - bookshelf
    - smooth_brick
    - smooth_stairs
    - glass
    - step
    - glowstone
    - huge_mushroom_1
    - huge_mushroom_2
    #- iron_door_block
    - nether_brick
    #- note_block
    - log
    - wood
    - wood_stairs
    - nether_brick_stairs
    #- jukebox
    #- workbench 
    #- door
    - thin_glass
    - wood_plate
    - stone_plate
    - coal_ore
    - gold_ore
    - lapis_ore
    - redstone_ore
    - glowing_redstone_ore
    - iron_ore
    - diamond_ore
    - gold_block
    - lapis_block
    - iron_block
    - diamond_block
    - water_lily
inks:
    rose_red: dark_red
    dandelion_yellow: yellow
    lapis_lazuli: blue
    cactus_green: dark_green
    ink_sac: black
    bone_meal: white
    cyan_dye: blue
    purple_dye: light_purple
    gray_dye: dark_gray
    light_blue_dye: aqua
    pink_dye: red
    lime_dye: green
    magenta_dye: dark_purple
    light_gray_dye: gray
    coal: dark_gray
    glowstone_dust: gold
    redstone: magic
    #cocoa_beans: # no brown
    #orange_dye: # no orange


